name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t frontend-dev -f ./deploy/Dockerfile --build-arg FRONT_DOMAIN=\"\" --build-arg BACKEND_DOMAIN=\"\" --build-arg PROXY_TO_BACKEND=http:\\/\\/backend-dev:8080 .
